### ISSUE TITLE
Cannot use system certificates when fetching latest release

### ISSUE THREAD

**Issue by mchernicoff** [axodotdev/axoupdater#132]
When fetching the latest release, `axoupdater` uses `reqwest` with just the default Mozilla Web PKI certificates, and does not pick up the system certificate store. There should be an option to support using the system certs.

The reason for wanting this is basically that some corporate network security software substitutes certificates with ones managed by the organization, and those substituted certs are rooted in one or more certs in the local system certificate store. If that store isn't picked up, then any request whose certs are substituted will fail certificate validation.

**Comment by ashleygwilliams** [comment]
closed by https://github.com/axodotdev/axoupdater/pull/136
