### ISSUE TITLE
Self updater doesn't respect package manager installation if cargo-dist installation occurred before

### ISSUE THREAD

**Issue by konstin** [axodotdev/axoupdater#34]
The self updater ignores that the currently running binary was installed by a package manager if the recipe is present because a different cargo-dist curl installation happened before.

This is based on https://github.com/astral-sh/uv/pull/2228

Let's install uv 0.1.14 through the cargo-dist curl installer first, then a package manager installation of 0.1.13 on top:

```
$ curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.1.14/uv-installer.sh | sh
downloading uv 0.1.14 x86_64-unknown-linux-gnu
installing to /home/konsti/.cargo/bin
  uv
everything's installed!
```

Let's install a different, also not up-to-date version. In this case i took https://github.com/astral-sh/uv/pull/2228, edited it to 0.1.13 and called `pipx run maturin build`.

```
$ pipx install /home/konsti/projects/uv/target/wheels/uv-0.1.13-py3-none-linux_x86_64.whl
⚠️  Note: uv was already on your PATH at /home/konsti/.cargo/bin/uv
  installed package uv 0.1.13, installed using Python 3.11.6
  These apps are now globally available
    - uv
done! ✨ 🌟 ✨
```

Or there's a different version of uv, let's remove it, or alternatively just change path precedence.

```
$ rm /home/konsti/.cargo/bin
$ which uv
/home/konsti/.local/bin/uv
$ uv --version
uv 0.1.13 (e73705607 2024-03-06)
```

Call the updater:

```
$ uv self update
success: You're on the latest version of uv (v0.1.13).
```

In this case, we should have gotten the "you're in a managed environment message", not the (incorrect) latest version.

**Comment by mistydemeo** [comment]
That's an interesting issue! Like you say, the presence of the receipt is the proxy we use to determine if it was installed by a package manager. Is there another method we could have used to determine if the binary was installed via a package manager for your usecase?

**Comment by konstin** [comment]
We could add a feature flag and only activate it for github releases builds. Otherwise, the binary should imo check that the recipe version is not the binary version

**Comment by charliermarsh** [comment]
Could we check if the currently-running executable is the same as the one that's going to be updated / replaced?

**Comment by mistydemeo** [comment]
Thought about this, and since we do have information about the installation root the receipt is for, we can compare that against the actively running EXE.
